### ISSUE TITLE
Unable to update chart data

### ISSUE THREAD

**Issue by hyyan** [angular-google-chart/angular-google-chart#154]
Hi , thanks for the great work but I have problem which I can not solve.

My code is something like : 

```
 $scope.chartObject = {
                            type: 'AreaChart',
                            options: {
                                legend: 'none',
                                hAxis: {showTextEvery: 5},
                                selectionMode: 'multiple',
                                tooltip: {trigger: 'selection'},
                                aggregationTarget: 'none',
                                chartArea: {
                                    width: 500,
                                    height: 150
                                }
                            },
                            data: {
                                cols: [
                                    {id: "t", label: "Date", type: "string"},
                                    {id: "s", label: "Data", type: "number"}
                                ],
                                rows: []
                            }
};
```

now what I want is to update chart rows from code every time I receive data from server like this:

```
$scope.updateData = function(){
           // do stuff

        $scope.chartObject.data.rows = [] // my new data
}
``

But chart is not affected by that.

Any Idea , please ?
```

**Comment by Balrog30** [comment]
Sorry I haven't gotten to this sooner (I usually answer within 24 hours, but it's been a busy week.)  I can't see anything clearly wrong here, so I'd need more to troubleshoot.  If you can post a working sample on [plunker](http://plnkr.co) it would make it a lot easier.

The debugging steps I would take on this particular problem would be as follows:

1. Make sure there are no errors in the JavaScript console.  If there are, fix those.
2. Make sure the code in `// do stuff` is executing.  If this code doesn't do anything you can observe directly, then add a `console.log()` or `$log.debug()` to your function so that you can tell it actually ran.  If it doesn't run, the function may exist on a different scope than your button or whatever you're using to trigger the function.  Skip ahead to step 5 to help figure out why.
3. Add the following code to your page/view/template that your controller is scoped to.  This will give you a nicely formatted json representation of your `$scope.chartObject` with two-way binding.  It should be on the same scope as your controller because that will help you figure out if you have scoping issues.
```HTML
<pre>{{chartObject | json:true}}</pre>
```
4. After completing step 3, run the function that is meant to be changing your chart data and be sure that it is actually changing. If the function is outputting to console as per step 2, but the data in `$scope.chartObject` is not changing in your view from step 3, then your function is probably running in a different scope than your chartObject.
5. If any of the above pointed to a scoping issue (that's what I'm leaning toward here since there was nothing else obvious), then look for the cause.  Usually it's a directive that creates it's own scope like ng-include, ng-repeat, a ui-bootstrap tab panel, or maybe even your own custom directives.

If none of this helped, I'll need more to go on to give advice.  By the way, a scoping issue is that happens when your function or object exist in a different $scope than the code that is executing.  If you make a request for a function or object that does not exist on the current $scope, it will look upward in the $scope tree for a match by name, but not downward to child $scopes.  I'm not sure about sideways to sibling scopes, but I don't think it does.  So if a child scope has it's own instance of `$scope.chartObject`, it will change that one instead of the one on the parent scope, and then the chart directive won't receive the change because it is watching on the parent.

**Comment by Adrien-P** [comment]
Hi,
I had a similar issue: I took one of the examples (with the onions etc.) and rather than updating my model with the user interface I wanted to do it when I received new data from the server.
The updated values in the $scope would only update when I clicked on an element of the chart (for example a bar in the BarChart)
After searching for a while I tried to put a $scope.$apply() just after updating my $scope values and it fixed all my issues.
In your example, I would put a $scope.$apply() after  $scope.chartObject.data.rows = [] // my new data

I hope it can help

**Comment by Balrog30** [comment]
I'm trying to clean up some old issues. Is this solved?
