### ISSUE TITLE
material charts

### ISSUE THREAD

**Issue by snothegg** [angular-google-chart/angular-google-chart#156]
Google added some new features called material charts
https://developers.google.com/chart/interactive/docs/gallery/columnchart#Material

some more advanced chart options are only available with them

http://stackoverflow.com/questions/17925722/stacked-column-chart-for-two-data-sets-google-charts
http://jsfiddle.net/p7o0pjgg/

it would be great if the module offered a way to configure loaded package (bar or corecharts) and handle the small differences

**Comment by Balrog30** [comment]
If you look in sample.js you'll see that you can set a value that is used by the app loader to load your chart packages.  The "subtle differences" is up to the user.  The only features that this project handles explicitly on some chart events and formatters.  Your data and options are just passed directly to the Google Api without modification or checks.  If there's a more specific issue with this chart type I can do more to help resolve it.

**Comment by snothegg** [comment]
sorry for my bad explanation
I created a small sample here: http://plnkr.co/edit/yAIlotrSqP5WNnVYHefA?p=preview
material charts are loaded now but for example the stacked feature is not working here 
My assumption is that its because of the wrong data type being used
From the docs 
>You load the Google Visualization API (although with the 'bar' package instead of the 'corechart' package), define your datatable, and then create an object (but of class google.charts.Bar instead of  google.visualization.ColumnChart).

unfortunately I could not find a way to change your module to use charts.Bar

**Comment by bouil** [comment]
In fact we do not create a specific chart type with the directive, but we rely on the ChartWrapper feature, that allow to specify dynamically which chat object must be created.

See https://developers.google.com/chart/interactive/docs/reference#chartwrapperobject

So all you have to figure out, is what "chartType" to use so the type of the cart is a material chart (google.charts.*) instead of a old chart (google.visualization.*). Maybe it's not possible, and if so, the directive must be adapted to do so.

**Comment by snothegg** [comment]
I think I found the solution, you just have to pass options in converted format
looks like they changed some namings: see http://plnkr.co/edit/yAIlotrSqP5WNnVYHefA?p=preview

so i just check in console the new name and use it (e.g. stacked instead of isStacked )
```javascript
options={isStacked:true,series: {
            1: {
                targetAxisIndex: 1
            },
            2: {
                targetAxisIndex: 1
            },
            5: {
                targetAxisIndex: 1
            }}}

 google.charts.Bar.convertOptions(options)

// results in 
Object {isStacked: true, series: Object, width: null, height: null, stacked: true…}axes: Objectchart: ObjectgroupSize: nullheight: nullisStacked: truelegend: ObjectselectionMode: nullseries: Objectstacked: truewidth: null__proto__: Object
```

thanks for your help, all good

**Comment by Balrog30** [comment]
I'm trying to wrap my head around these new changes to the Google API. @snothegg is kind of right here that it might be nice to handle these new changes in a graceful way.  Ideally there should be no dependency on the Google Charts API in an AngularJS Controller as this makes Unit Testing very difficult.  You would need to somehow fake the library to do Unit Tests, and you're bringing in a dynamic library for End-to-End testing.  I've mostly ignored all this so far because at first I wasn't testing, and also most requests from other users for help that required this were not "simple" cases.

This new shift from the Google team to "convert" the chart options does not play well with simple use cases and this directive.  It also gives a glimpse of a small but significant change on Google's part.  Most notably that the chart objects used to be named something like `google.visualization.BarChart`, and the new naming convention is more like `google.charts.Bar`.

This makes handling the new Material Design features a little more complicated.  We would need to somehow take input from the directive users to figure out if they want to use Material Design or the old charts.

I'm also very curious what the `convertOptions()` method does.  I'll do some playing around later to see what the output is.  I was thinking we could use JavaScript's dynamic nature to see if the `convertOptions()` method exists on the type for the chart being used and run it if needed, but the difference in namespace between the new charts and old charts makes me think twice about whether that is possible.

Thinking and typing as usual... I'll report back once I've experimented with Material Design a bit.

**Comment by Balrog30** [comment]
I was intrigued enough about this topic to go digging.  I've gotten the Material Design versions of Bar Chart and Line Chart to work with Angular-Google-Chart.  You need to load the packages for the new charts, and set the chart type to `google.charts.Bar` or `google.charts.Line`.  For anyone interested, I added a post to my much-neglected blog on the subject. http://nicholasbering.ca/angularjs/2015/02/10/agc-material-bar/

**Comment by bouil** [comment]
Nice post !

2015-02-11 5:51 GMT+01:00 Nicholas Bering <notifications@github.com>:

**Comment by RakanNimer** [comment]
It looks like the API design for the Material Design ChartWrapper, but will be in future versions. In the meantime you can get the look and feel of the new api by setting the **theme** in the options literal to material.
https://groups.google.com/forum/#!topic/google-visualization-api/xV8ehAVNvvE

**Comment by Balrog30** [comment]
@RakanNimer I don't understand what you're trying to say. But yes... the google groups post you linked to is me, asking about this topic.  I afterwards fleshed this out into more detail in the blog post I linked to above.
