### ISSUE TITLE
Example loading data from remote

### ISSUE THREAD

**Issue by pietromarrone** [angular-google-chart/angular-google-chart#190]
I'm having problem loading data from a remote server either with json array and with Data Source Library implemented with google-visualization-java on own server.

It seems that Angular does not wait for: handleDsResponse
query = new google.visualization.Query(url);
query.send(handleDsResponse);

If I resize the window then the chart appear

Is there somewhere an example?

**Comment by pietromarrone** [comment]
Maybe can help this, wrapping query.send in $intervall even with 0 it works

$interval(query.send(handleDsResponse),0);

**Comment by Balrog30** [comment]
I've never worked with a data source that implements the Google Charts Data Source interface. If someone can point me to a public data source I'd consider doing some playing around, but otherwise I'd be unable to test this out.

I think I can make a leap and assume that most users are using $http to acquire data if I've never seen questions about this before.

**Comment by pietromarrone** [comment]
Yes, this is the reference for [Chart Tools Datasource protocol] (https://developers.google.com/chart/interactive/docs/queries), Some examples of Datasources include Google Spreadsheets, Google Fusion Tables, and SalesForce, or you can implement it you own. 

This is an [example from fusion table] (http://www.google.com/fusiontables/gvizdata?tq=SELECT%20%27Scoring%20Team%27,%20%27Receiving%20Team%27,%20%27Scorer%27,%20%27Minute%20of%20goal%27%20FROM%20%22%20+%20%221VlPiBCkYt_Vio-JT3UwM-U__APurJvPb6ZEJPg)

it returns an JSON object 
```javascript
google.visualization.Query.setResponse({
version:'0.5',
reqId:'0',
status:'ok',
table:{
   cols:[
      {id:'col0',label:'Scoring Team',type:'string'},
      {id:'col1',label:'Receiving Team',type:'string'},
      {id:'col3',label:'Scorer',type:'string'},
      {id:'col2',label:'Minute of goal',type:'string'}
    ],
    rows:[
      {c:[
            {v:'South Africa'},
            {v:'Mexico'},
...


Could be usefult to instruct how tu use it as Datasources too.

Regards

**Comment by pietromarrone** [comment]
After further investigation I found that the problem is not the extrenale Datasources, 
but the handler method of query.send

**Comment by Balrog30** [comment]
So... as I understand the issue you're having, it's all about when the chart draws?

In my own code I am using $http to get my data from an ASP.Net Web API back-end, which is returning some data formatted as a google charts data table in JSON. I resolved empty data table by running things in this order:

 1. Instantiate controller with variable `$scope.loading = { chartData: true };`
 2. `$http.get(dataSourceUrl).then(...)`
 3. Success handler sets `$scope.loading.chartData = false;`

View has something like this:
```HTML
<div google-chart chart chart="chartObject" ng-if="!$scope.loading.chartData"></div>
<div ng-if="$scope.loading.chartData">
    <img src="/images/spinner.gif" />
</div>
```

The basic idea here is that you're hiding your chart until you have data to display in the chart.  I think this is what you were getting at, except that instead of `$http` you're using `google.visualization.Query` to get your data.

An alternative to the method above, if you are using a router like **ngRoute** or **ui-router**, is to put your data in the route resolves.  The downsides to this are that slow loading data will slow your route loading, and a failed data load will cause the route change to fail.  Route change failure could be problematic if you wanted to show the view even if the data failed to load.  Querying your data source with `google.visualization.Query` could still be done in a route resolve, but you would have to wrap the query with an angular promise.  I can show you how if you're interested.

If, on the other hand, you are trying to tie your data source directly to the chart, that is a feature supported by Google Charts API, but I am not aware of any way to do that with angular-google-chart as it stands today.
