### ISSUE TITLE
Make Demo for responsive

### ISSUE THREAD

**Issue by vaneshmali** [angular-google-chart/angular-google-chart#200]
I am looking over this:
http://plnkr.co/edit/E4iPtQ?p=preview

It is not responsive.
I also gone through this : https://github.com/angular-google-chart/angular-google-chart/pull/97

Still the chart is not going to become responsive.

__calling:__ beforeDraw="maintainRatio(chartWrapper)"  as you said. 
__style for the same div as:__ style="height:100%;width:100%"

maintainRatio is in my controller.
Using __ng-google-chart.js__ (latest commit: version- 0.0.11)

**Comment by Balrog30** [comment]
If I get some time I'll tinker around with this issue again to come up with a recommended way to do this.  Honestly, pretty busy lately so I don't know when I'll get to it.

I have this working in my own project but it required a lot of tinkering to get it to work.  So much so that when I finally got it working I probably couldn't even figure out what it was I did that fixed it, and as such it's hard to repeat.

**Comment by vaneshmali** [comment]
There should be a standard and easy way to do it. Hope it will...!!! Waiting for the same.

**Comment by vaneshmali** [comment]
Did the same as @yifange's working example. Not worked in my case. Everything is same, updated ng-google -chart.js as of 15th July 2015.  __ Updated:  //Cleanup resize handler.
                $scope.$on('$destroy', cleanup); __ . Still blocked: Not responsive yet.!!!

**Comment by yifange** [comment]
@vaneshmali If you can reproduce it and share your code in a Plunkr, I can have a better look at it.

**Comment by vaneshmali** [comment]
@yifange Created http://plnkr.co/edit/ZOTk6MVi2D5hlLdPbc7K?p=preview 

Its working fine as per expectation, but not in project! Why so? I am using requirejs-angularAMD.

**Comment by yifange** [comment]
@vaneshmali Can you try to integrate angularAMD in your example? Even if it seems irrelevant...
