### ISSUE TITLE
`Chart Object not defined` error and `googleChartApiPromise` undefined.

### ISSUE THREAD

**Issue by piyushchauhan2011** [angular-google-chart/angular-google-chart#208]
I'm trying to use `angular-google-charts` with `$http` service to fetch the data and populate the charts. For that I followed the tutorial from this blog post: http://nicholasbering.ca/angularjs/2015/04/02/google-charts-api-promise/ because github README for `angular-google-charts` don't have examples showing the backend data service.

I'm getting this error:

[![Chart Not defined][1]][1]

    function SomeCtrl(
      $scope,
      $log,
      $stateParams,
      googleChartApiPromise,
      $http,
      $q) {

        googleChartApiPromise.then(function() {

          $scope.goodsAndServicesChartObject = {};

          init();

          function init() {
            var dataPromise = $http.get('businesses/' + $stateParams.businessId + '/contact_users/gender');

            $q.all({
                data: dataPromise,
                api: googleChartApiPromise
              })
              .then(apiLoadSuccess);
          }

          function apiLoadSuccess(result) {
            $scope.goodsAndServicesChartObject.type = 'PieChart';
            $scope.goodsAndServicesChartObject.options = {
              'title': 'Goods Vs Services'
            };
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Value');
            data.addRows(result.data.data);

            $scope.goodsAndServicesChartObject.data = data;

          }
        });
      }

Sometimes it loads the image when `googleChartApiPromise` is not `undefined`.

[![Chart][2]][2]

  [1]: http://i.stack.imgur.com/TU9M2.png
  [2]: http://i.stack.imgur.com/cKbuZ.png

I'm wondering why `googleChartApiPromise` get undefined sometimes ?

@Balrog30

**Comment by piyushchauhan2011** [comment]
Also I was reading through the code `googleChartApiPromise` source and it loads the google charts and append to DOM each time promise is used on a page. So in my case I have three tabs and each tab has its own controller which is using the `googleChartApiPromise` service and using `then` to populate the data and attach to chart object.

**Comment by Balrog30** [comment]
Regarding your second comment about the promise:

I haven't actually run experiments to confirm the behaviour, but here's how I understand it.  Factories in Angular produce a singleton object.  It runs the factory method once, and then after that it injects whatever your return from the factory method whenever someone calls it. If you can produce an experiment to show me that it injects the script multiple times, then I will fix it.

Regardin the actual issue:

The little red box you are showing as your error looks like the one that Google Chart API injects where your chart will go when it finds an error.  This happens because the $scope.goodsAndServicesChartObject is an empty object at the beginning.  The charts library needs at least the chart type, and data to be defined to draw a chart. When I actually do this in product I usually hide the chart with `ng-if` (important to use `ng-if` and not `ng-show`) to remove the chart until it's actually ready to show.

I might be wrong here, but I'm just going by what I see.  Without a working sample I can never really tell what the actual problem is.

**Comment by Balrog30** [comment]
Also, I know you're not looking for a code review, but I built the article example with very specific requirements.  There are no anonymous functions, and no logic runs inside the controller instructor directly (hence the init function).  You've rebuilt this so that **everything** is inside an anonymous function.  It just kind of defeats the purpose.  If you want to know more about why I built it this way, see https://github.com/johnpapa/angular-styleguide.  It was started by @johnpapa, but has over 100 contributors from the community to help set best practices for AngularJS code.

**Comment by bouil** [comment]
Still about code review, in your sample using the "googleChartApiPromise.then" is useless because it's already implicitly included in the "$q.all" call.

**Comment by Balrog30** [comment]
I should also point out that you don't actually need to use the Google Charts API to populate a chart's data table.  Getting data from an $http request doesn't change this fact any.

A couple of examples for when you DO need to use the Charts API:
* You want to query the chart data using the api to change some options on your chart at setup.
* You want to use some feature of the Charts API that is easier to access from the API directly, for example...
  * HTML Tooltips (DataTables from arrays does not support this, and the JSON DataTable format can be somewhat confusing to write manually)
  * Column Roles
  * Any kind of data query
* You want to dynamically build your chart in real-time from User input. This can still be done with array or JSON initializer formats, but might be easier to wrap your head around it by just using the `addRow()` method supplied by the `google.visualization.DataTable` prototype.

My own project has some heavy interaction between the data and the way it is displayed, so there is a lot of code calling the Charts API directly, but if it is a chart that simply displays some static data to the user then you will probably be able to get away with just setting up a chartObject and handing it off to the directive.

**Comment by piyushchauhan2011** [comment]
Thanks @Balrog30 I included the `ng-if` and remove `googleChartApiPromise.then` as specified in code review from @bouil. It works perfectly :smiley: . Will use the guidelines as specified. As a starter it was little hard though to understand how the example will work with `$http`, it would be nice if you can include some examples of `$http`, `$resource` and custom things that one can do using `google-chart` api.

:+1:

**Comment by Balrog30** [comment]
Thanks for the feedback.  I'm working on a slightly more complete documentation branch. No definite timeline on that, but maybe in the next month.
