### ISSUE TITLE
Google Annotation chart is not changing the size

### ISSUE THREAD

**Issue by WaseemQawasmi** [angular-google-chart/angular-google-chart#225]
I'm using google annotation charts, and it works very well on the dashboard, but if I place the chart inside a Modal it will not change its size! but if I minimized the browser window and maximized it again, the chart size will change!

the below is the annotation chart div:

    <div google-chart chart="MWChartObject" style="height:500px; width:100%;" class="googlechart"></div>
![googlechartinsidemodal](https://cloud.githubusercontent.com/assets/12068667/10190284/2d0932c0-6774-11e5-8dad-a82c574d9bf9.png)

**Comment by Balrog30** [comment]
You may have stumbled upon a known quirk of the **Google Charts API**. If, at the time that the chart renders, the element is hidden, then the chart will not draw to your expected size. This is because the Charts API uses the element size to determine what size to render, but when hidden and element has no size.

I usually get around this sort of problem by putting an `ng-if` directive on or above the chart element with an expression that will not return true until I am certain that the element will be shown. The next best solution is to set a fixed size on the chart. You could always calculate that size, but as long as the size is given in the chart options, it will render that size and not some other random width and height.

If neither of those seem to work for you, you could try to force a redraw after the chart has been displayed by changing some insignificant chart option (it doesn't even have to be a real option), or changing something on your data. Using scope to broadcast `'resizeMsg'` will also force all charts to redraw. Just make sure the chart element is actually visible when this happens or it will just render to that odd size again.

If you still have issues, I will need more information to be able to help diagnose the issue.  I will need the version of angular-google-chart, AngularJS, and some information about how you are displaying your modal dialog. Live code samples like plunker, jsFiddle, CodePen, or any other platform that shows the issue in action are of great help.

**Comment by WaseemQawasmi** [comment]
Thank you @Balrog30 , fixed by putting fixed size inside the options.
