### ISSUE TITLE
Add hover listener on Annotation chart

### ISSUE THREAD

**Issue by WaseemQawasmi** [angular-google-chart/angular-google-chart#226]
Hi,
How can I add hover listener on angular google annotation chart, I tried to make it using jQuery, but it will get all the events on the path not only on points.
I tried:  "google.visualization.events.addListener($scope.chartWrapper, 'onmouseover', function (){alert("mouseOver"); });" also it not worked.. How can I make tooltip or display more data for specific point on chart by hover.

**Comment by Balrog30** [comment]
I have a solution for you but am on my phone at the moment, so it's a little hard to type code.  I'll give you a full and proper response within the day.

**Comment by Balrog30** [comment]
If you are using the most recent version (0.1.0-beta.2), it includes an `agc-on-mouseover` directive. There's a little bit of documentation on how to use it in the description to PR #215.

Manually adding an event listener in the manner you described does not work because the chartWrapper does not pass on events specific to the underlying chart type. Even though onmouseover is a pretty common event which is available on most charts, you will have to register it on the child chart object.

I suggest using the directive in the newer version rather than trying to write your own solution, because it also handles things like registering the listener again if the underlying chart object changes. If you need more explicit directions on how to use it, I would request more details on what you are trying to achieve so that I can tailor an example to your use case.

**Comment by WaseemQawasmi** [comment]
@Balrog30 IT worked :) Thank you very much!
