### ISSUE TITLE
flickering tooltip on chart

### ISSUE THREAD

**Issue by nealshan2** [angular-google-chart/angular-google-chart#285]
![image](https://cloud.githubusercontent.com/assets/9512651/16971421/3403c86e-4e56-11e6-8731-389b2f20e99c.png)

As you can see, while we hover on tooltip's border, and the cursor was on tooltip's border and chart, it was flickering.

**Comment by nbering** [comment]
Sorry, this problem is upstream, not much I can do about it, but there may be some work-arounds. See google/google-visualization-issues#2162

It probably wasn't an issue before, but the charts team updated the version on the loader endpoint we're using on July 1st, so some old issues may be fixed, but unfortunately that sometimes comes with new bugs. I'm working on a solution for loading from whatever endpoint you choose.

**Comment by nealshan2** [comment]
Thanks @nbering ,  Just got solution from https://github.com/google/google-visualization-issues/issues/2162

`svg > g > g:last-child { pointer-events: none }`
