### ISSUE TITLE
Material Chart "Bar" not working

### ISSUE THREAD

**Issue by vnreddy9** [angular-google-chart/angular-google-chart#288]
When we use the chart type "Bar" its not working from few days before that it works great.
Here is the error "VM829:38 Uncaught ReferenceError: O is not defined"

**Comment by nbering** [comment]
Apologies, but your description of the error doesn't give me much to go on. Amongst other things, your error points to some sort of dynamic code, rather than a line number, so I can't say whose code the error belongs to.

What I can say, is that sometimes there are issues loading the Google Visualization API, and clearing the browser cache may resolve such issues. Other than that, I need more information or I can point you to the upstream issues repository at https://github.com/google/google-visualization-issues/issues.

**Comment by nbering** [comment]
No response and way out of date. Closing.
