### ISSUE TITLE
Broadcasting resizeMsg does nothing and altering chart.options values doesn't update the graph

### ISSUE THREAD

**Issue by Forgetyo1sttime** [angular-google-chart/angular-google-chart#289]
Hi, I'm using your module coupled with another one called angular-slider. I'm using it to obtain a date range and then show the graph according to that same date range.

I have a callback for the changes ocurring in the slider so I was expecting that calling the resizeMsg event on that callback would redraw the graph with new values. This is my code:

`hAxis: {
                        viewWindow: {
                            min: (vm.slider.value - vm.slider.options.floor) / (1000 * 60 * 60 * 24) - 2,
                            max: (vm.slider.high - vm.slider.options.floor) / (1000 * 60 * 60 * 24)
                        },
                        "title": "Date"
                    }`

(all those multiplications are because the time is in milliseconds)

vm.slider.value is the lower date and vm.slider.high is the higher one. vm.slider.options.floor is the lowest possible value. I use this to obtain the index corresponding to the minimum and maximum dates selected in the slider.

The issue I'm having is that broadcasting resizeMsg doesn't change anything in the graph and neither does updating any options variable. I log the values of vm.slider and they change properly and the whole line corresponds to the index properly but nothing changes.

Thank you

**Comment by Forgetyo1sttime** [comment]
Further testing I noticed it does trigger the event when I call it on the onChange event on the slider, however, the graph doesn't change at all

**Comment by nbering** [comment]
I'll see what I can do to help. I'm afraid the little snippet you've included is very important to you, but is not a complete statement, so it does nothing to help me debug the issue. The best thing for me to help you would be if you could reduce this down to the base problem in a jsFiddle or some other live code demo platform. If that would be too difficult, I at least need to see what takes place when the controller is in instantiated, what happens when you get your changed event, and when you are broadcasting the message.

I suspect what's happening here is that you are calculating your values once to assign the object, and somehow expecting the values inside that object to recalculate themselves again on the fly. JavaScript does not work that way. It resolves the expression to a value and then assigns the value, whatever that may be, with no history of how that value came to be. If that's not what's happening, I'll need more information to help you figure this out.

**Comment by Forgetyo1sttime** [comment]
I think you might be on to something on that second guess. I can't really get a JSFiddle since it's a large snippet. However, here's most of the code I believe might be relevant:

`                    onChange: function (id) {` 
                  `       console.log((new Date(vm.slider.value)));` 
                     `    $rootScope.$broadcast('resizeMsg');` 
                    ` }`

This is the event I was talking about which is called when any changes are registered in the slider.

The controller instantiation is pretty basic and all of the other options for the myChart object are the same as the examples, with it being populated with data with the following format:

`Date | value1 | value2`
`'25-12-2015 | 1.23     | 25.4'`

I tried getting the date to be of date type but I settled for string. As such, the calculations done in my OP are done to get the correct index of the array passing from milliseconds to days, which corresponds to day 0, 1, etc on the array.

The values are calculated once and it's working fine on the first time with the viewWindow applying to the calculated values. However, when the values of vm.slider change it doesn't change the viewWindow min and max values, even after a redrawing.

I know I'm not the best at explaining and I'm probably making it really hard for you to help me, but I really appreciate it and if anything else is needed I'll provide it.

**Comment by nbering** [comment]
What I see here is, you're broadcasting the resizeMsg, but I don't see any code that actually mutates the chart data or options. As such, the chart is just going to redraw with nothing different.

**Comment by Forgetyo1sttime** [comment]
vm.slider.value and vm.slider.high are changed when I move the slider as I log their values on the callback and they indeed change. Don't the hAxis.viewWindow.max and min values change if the values they are assigned change as well?

`hAxis: { viewWindow: { min: (vm.slider.value - vm.slider.options.floor) / (1000 * 60 * 60 * 24) - 2,`

**Comment by nbering** [comment]
Ok. Let's go over this. 

Controller:
```js
function myAngularController($scope, dataService)
{
  var x = 10;
  $scope.sliderChange = onChange;
  $scope.myChart = {};
  init();

  // ------

  function init()
  {
    $scope.myChart.type="ColumnChart";
    $scope.myChart.data=dataService.getData();
    $scope.myChart.options = {
        title: "My Awsome Profound Data!",
        width: 1000/x
    };
    console.log($scope.myChart.options.width); //100
  }

  function onChange()
  {
    x = 5;
    console.log($scope.myChart.options.width); //100
    $scope.broadcast("resizeMsg");
  }
}
```

In the example above, the chart's options are a calculated value: `1000 / x`. When you assign this to the options, you are not assigning the expression `1000 / x`, you are assigning the resolved value from the expression. In this case `1000 / x` = `1000 / (10)` = `100`. So later on, if I change `x`,  `$scope.myChart.options.width` is still `100` because I never reassigned it. Changing `x` only changes `x`.

**Comment by Forgetyo1sttime** [comment]
Yeah, I don't know how I didn't think about that. Thanks and sorry for the trouble! Keep up the good work!
