### ISSUE TITLE
Google chart with bootstrap accordion 

### ISSUE THREAD

**Issue by jagathish** [angular-google-chart/angular-google-chart#300]
Hi,, Im using bootstrap accordion, so graph not working properly, i need to redraw chart onclick event.. Please let me know if you know any solution for this ..

**Comment by nbering** [comment]
Are you mixing angular with Bootstrap's own code, or are you using ui-bootstrap?

Can I see some of your view code?

**Comment by jagathish** [comment]
Yes im using ui-bootstrap..  please check the link http://codepen.io/jagathish/pen/bBOMEJ same issue is there... its not working properly. Please let me know if you know any solution.

**Comment by nbering** [comment]
Here's a working fork of your pen.

http://codepen.io/nbering/pen/PbXXxr

You'll note that Tab 1 sometimes still has issues drawing all three charts because they are the same chart object. Don't do that. It causes race conditions with the scheduling of rendering. Your other panel works fine.

### What was wrong?

CSS `display:none;` is often used to hide things. Hidden elements do not have a width or height. Google Charts uses the width and height to render the chart. Being hidden breaks that.

### What fixes this?

Putting an ng-if on your chart element fixes the `display: none` issue because ng-if actually removes the DOM element if the expression is falsey. That means the directive doesn't get compiled until the width and height of the container have been set. An alternative is to set a fixed width and height from the chart options, but the developers at google have warned me that this still causes issues with font sizing.

### Changes to your pen

Controller code:

```javascript
$scope.tabStatus = [];
```

Accordion group:
```html
<div uib-accordion-group class="panel-default content-box" is-open="tabStatus[0]">
```

Chart(s):
```html
<div google-chart chart="chartAge" style="{{cssStyletwo}}"  ng-if="tabStatus[0]"></div>
```

**Comment by jagathish** [comment]
Hi,
thanks for your response... Tab 1 sometimes still has issues drawing all three charts because of "type :Bar " .. i gave type is Bar thats why is not working properly... i changed type to BarChart then its working fine... please check the given link.. 
http://codepen.io/jagathish/pen/bBOMEJ

**Comment by nbering** [comment]
The very fact that you have `chart.displayed = false;` in your controller suggests that you were fighting the directive internals. It's the only property of the chart object that the directive sets, and it's used internally to help schedule drawing of charts. I'm not sure if I'll finish it before I need to get some work done, but I'm updating my fork of your pen to show a fixed version.

**Comment by nbering** [comment]
Ok. Working through it, you could be right about the material Bar. It still acts up when I make the charts referentially unique. This may require some further investigation. I thought this problem was solved from Google's end.

**Comment by jagathish** [comment]
Any other option to fix this issues?? Bar type is not working properly

**Comment by nbering** [comment]
This one's out of my hands I'm afraid. The actual issue is with the upstream Google Charts API. If I find some time I'll see if I can diagnose the issue or find a work around but there's not much else I can do.

**Comment by nbering** [comment]
Closing as upstream.
