### ISSUE TITLE
not able to fetch image path for downloading option.

### ISSUE THREAD

**Issue by LuqmanParavetty** [angular-google-chart/angular-google-chart#304]
I have used angular-google-chart. But need an option to download like google chart gives an option eg: https://developers.google.com/chart/interactive/docs/printing

i followed some steps from here (https://github.com/angular-google-chart/angular-google-chart/issues/62) But not triggering the objects while on-ready of my element.

```
`  $scope.initChartImg = function (chartWrapper) {
      //console.log("chart image: ", chartWrapper);
        var chart_div = document.getElementById('chart_div');
        console.log(chart_div.innerHTML);
        var chartObject = chartWrapper.getChart();
        chart_div.innerHTML = '<IMG src="' + chartObject.getImageURI() + '">';

    };` 
```

`<div id="chart_div" google-chart chart="summaryChartData" style="height:500px; width:100%;" on-ready="initChartImg(chartWrapper)"></div>`

Please suggest me what is wrong in this

**Comment by LuqmanParavetty** [comment]
got know the issue & updating here as well.
change as it is mentioned below.

OLD: on-ready="initChartImg(chartWrapper)"
NEW: agc-on-ready="initChartImg(chartWrapper)"

Please close this issue.

**Comment by rgupta6** [comment]
Hi @nbering : I also had similar requirement and when I try to use 'chartObject.getImageURI()', it says getImageURI method is not available. Below is my method where I am trying to fetch the image URI:

initChartImg(chart1: GoogleChartComponent) {
    const wrapper = chart1.chartWrapper;
    var chartObject = wrapper.getChart;
    var imageURL = chartObject.getImageURI();
  }

![image](https://user-images.githubusercontent.com/17848933/84803489-f9bf4200-aff9-11ea-9ba7-2d03d8d65c24.png)

Could you please help me here

**Comment by nbering** [comment]
@rgupta6 That's weird. It's been a while since I wrote much TypeScript, but I don't recall there being method validation on the `any` type.

To get typings for Google Charts library stuff, try the [@types/google.visualization](https://www.npmjs.com/package/@types/google.visualization) package:

```
npm install --save-dev @types/google.visualization
```

Any of the types that extend [`ChartBaseRenderable`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/30d002292ec9906b90fbede67e1f99a928d8e7fb/types/google.visualization/index.d.ts#L598), or by extension [`CoreChartBase`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/30d002292ec9906b90fbede67e1f99a928d8e7fb/types/google.visualization/index.d.ts#L602) should have the `getImageURI()` method.

For canonical reference, check the "methods" section of the documentation for the chart type you're using. Here's a link to [Bar Chart methods](https://developers.google.com/chart/interactive/docs/gallery/barchart#methods) as an example.

**Edit**: I don't have typings for the angular component, and won't take the time to write them, since AngularJS will be End-of-Life sometime soon, if it isn't already. You can still leverage the typing from `@types/google.visualization` by using [casting/type assertions](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) in typescript to tell the compiler what type of chart you expect to receive here.
