### ISSUE TITLE
Chart tag holder must be explicitly closed (i.e. <div></div> and not <div />)

### ISSUE THREAD

**Issue by Jin-** [angular-google-chart/angular-google-chart#31]
Not sure if it is possible but I am struggling to see an option to setup multiple GoogleCharts. I know you can flip one chart into different types and change the data, but when you want to show multiple....

**Comment by Balrog30** [comment]
I learned a little bit more about this recently. I can't remember what the source was, or I would link it. It would seem that tags like `<input />` are called void tags, and cannot have inner content or children. Therefore `<div />` is not well-formed HTML, because `<div></div>` exists only have to content. The issue runs deeper into browser implementation than just an angular thing. I'm not sure if it would work if it was an element directive instead of an attribute directive. I'll keep this in mind when testing future versions, but I think this can be closed.  There's not much hope of changing this as long as the chart is assigned to a div element.
