### ISSUE TITLE
Can't bind dynamic data to pie chart but working on column chart.

### ISSUE THREAD

**Issue by ravisankarnair** [angular-google-chart/angular-google-chart#323]
The values are not taken, pie chart showing `100%.

` $scope.myChartObjectPie.data = {"cols": [
        {id: "t", label: "Topping", type: "string"},
        {id: "s", label: "Visits", type: "number"}
    ], "rows": [
        {c: [
            {v: "Dining"},
            {v: $scope.dining},
        ]},
        {c: [
            {v: "Home Delivery"},
            {v: $scope.homedel},
        ]},
        {c: [
            {v: "Take Away"},
            {v: $scope.takeaway},
        ]},
        {c: [
            {v: "Reservation"},
            {v: $scope.reserv},
        ]},
        {c: [
            {v: "Deals"},
            {v: $scope.deals},
        ]}
   ]}; `

**Comment by nbering** [comment]
You came to the right place for help with angular-google-chart!
Unfortunately, your issue as presented is missing some information for me to be able to help you.
Please make sure to include any relevant JavaScript *and HTML*. It would be even better if you could
provide a link to a [plunker](http://plnkr.co) or similar live code demo so that I can see the
issue in action.

Please also provide any Browser Console errors, including the stack trace.

The following may also be helpful:
- Version of AngularJS used
- Version of Angular-Google-Chart Used
- Any custom Google API settings applied
- Browser and Version

Lastly, be sure to provide any code samples with the fenced code block style (tripple backtick) of markdown code block (as opposed to inline code - single backtick), and friendly readable code formatting.

**Comment by nbering** [comment]
@ravisankarnair I'm assuming you're figured this out. If you're still having trouble I'll re-open for you.
