### ISSUE TITLE
`BoxPlot chart?

### ISSUE THREAD

**Issue by Dhananjayi9** [angular-google-chart/angular-google-chart#337]
its not issue but request can you add boxplot library as  well??

**Comment by nbering** [comment]
Will [Candlestick Charts](https://developers.google.com/chart/interactive/docs/gallery/candlestickchart) work for you?

**Comment by Dhananjayi9** [comment]
i have tried but its not working for me so i am looking specifically for BoxPlot chart

**Comment by nbering** [comment]
Sorry. I have no interest in adding support for other chart libraries, but if you want you can integrate a custom chart from another library with the wrapper if it provides consistency with other charts you are using. You'll need to implement the interface with the Google Charts API yourself.

See [Creating New Chart Types](https://developers.google.com/chart/interactive/docs/dev/).

Add your custom chart to the global namespace in JavaScript, and you can set the chart type to the class name of your chart. For example, if your chart class is `myApp.charts.BoxBlot`, then that's what the chart type would be.

I've always wanted to implement some more charts this way using D3, but working with the Google Charts DataTable structure. Honestly, though... I just keep this library in maintenance mode for now. I haven't been using it myself for some time.

If someone wants to make a PR with improvements, I'd be all for it... but wrapping around other libraries I probably wouldn't support because when people ask for help - like you are now - I still provide support from my knowledge of this library and Google Charts in general. I'd rather not pull in something I don't understand.
