### ISSUE TITLE
getChartLayoutInterface not fully implemented?

### ISSUE THREAD

**Issue by shahinlotfi** [angular-google-chart/angular-google-chart#344]
Hi,

I can apply the getChartLayoutInterface() function to the chart, however none of its methods work beyond that.

getBoundingBox
getChartAreaBoundingBox
getHAxisValue
getVAxisValue
getXLocation
getYLocation

Are these not implemented, or am I doing something wrong?

Thanks

**Comment by nbering** [comment]
I have a blog post on the layout interface here:
https://nicholasbering.ca/angularjs/2015/08/09/agc-image-overlay/

Keep in mind that the chart needs to be "ready" for this to work, so I've used the "ready handler" of the angular component. If you call it immediately, the chart may not have rendered yet, so there wouldn't be any coordinates, yet.

**Comment by nbering** [comment]
Also keep in mind that not all chart types implement the layout interface. Some charts (OrgChart, CalendarChart, Maps, etc...) are built in a way that wouldn't make any sense to implement the methods needed for the layout interface, since they don't have contiguous axes. For others, they might pre-date the interface, or are not a complete chart implementation.

If a chart supports the interface, it should appear in the "methods" section of the documentation for that chart type. Here's an example link for the column chart.
https://developers.google.com/chart/interactive/docs/gallery/columnchart#methods

**Comment by shahinlotfi** [comment]
Thank you! It's all working nicely now!
