### ISSUE TITLE
Gauge charts not working

### ISSUE THREAD

**Issue by fo2sh04** [angular-google-chart/angular-google-chart#350]
Hello,
i have used angular-google-chart to visualize a Gauge chart and it was working perfect,
suddenly , i open the page today show that no charts visible without any change in the code ,
also when i'm trying the following example you provide it's not working http://plnkr.co/edit/3RJ2HS?p=preview&preview

also i have tried this simple example in the documentation http://angular-google-chart.github.io/angular-google-chart/docs/latest/examples/gauge/
not working also 

Note : there is no issue in the console.

would you please provide me a help ?

Thanks in advance 
Fouad Ahmed.

**Comment by nbering** [comment]
Are you still having trouble with this?

The plunkr example you linked uses are very old version of both AngularJS (1.05) and this project (pre-GitHub org). It doesn't work for me, but it seems like Angular is just outright broken because I'm seeing raw templates in the view.

The example for our docs page is working fine for me.

It's possible that you're having trouble loading the Google Charts library. In the past, I've seen it fail to load when the Google development team pushes a release, and some caching failures would break the loader... but that hasn't happened in a while. I've also heard of some firewalls (corporate or government) blocking Google domains, which could also break the loader.

**Comment by nbering** [comment]
Closing, as I could not replicate the issue, and there was no response to my inquiry. If this was not a temporary problem, and you still need help... I will re-open this issue for you.
